apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgresql
  name: postgresql
spec:
# Use "LoadBalancer" if you want an external IP for your service to connect from external tools
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    name: postgresql
