apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgresql
    spec:
      containers:
      - image: postgres:9.5
        name: postgresql
        env:
          - name: POSTGRES_PASSWORD
            # Change this password!
            value: postgres
        ports:
          - containerPort: 5432
            name: postgresql
